document.body.dataset.theme = localStorage.getItem('neon-coil-theme') || 'lime';
if (localStorage.getItem('neon-coil-fullscreen') === 'true') document.addEventListener('pointerdown', () => document.querySelector('.shell').requestFullscreen().catch(() => {}), { once: true });
document.addEventListener('fullscreenchange', () => localStorage.setItem('neon-coil-fullscreen', document.fullscreenElement ? 'true' : 'false'));
const boardEl=document.querySelector('#board'), minesEl=document.querySelector('#mines-left'), statusEl=document.querySelector('#status'), startBtn=document.querySelector('#start');
const size=10,mines=10;let cells,gameOver;
function reset(){gameOver=false;cells=Array.from({length:size*size},(_,index)=>({index,mine:false,revealed:false,flagged:false,count:0}));let spots=[...cells].sort(()=>Math.random()-.5);spots.slice(0,mines).forEach(cell=>cell.mine=true);cells.forEach(cell=>{cell.count=cells.filter(other=>other.mine&&neighbors(cell.index).includes(other.index)).length;});minesEl.textContent=mines;statusEl.textContent='READY';render();}
function neighbors(index){let x=index%size,y=Math.floor(index/size),result=[];for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){let nx=x+dx,ny=y+dy;if((dx||dy)&&nx>=0&&nx<size&&ny>=0&&ny<size)result.push(ny*size+nx);}return result;}
function reveal(cell){if(gameOver||cell.revealed||cell.flagged)return;cell.revealed=true;if(cell.mine){gameOver=true;cells.filter(item=>item.mine).forEach(item=>item.revealed=true);statusEl.textContent='GAME OVER';}else if(cell.count===0)neighbors(cell.index).forEach(index=>reveal(cells[index]));if(cells.filter(item=>!item.mine&&!item.revealed).length===0){gameOver=true;statusEl.textContent='YOU WIN';}render();}
function render(){boardEl.style.gridTemplateColumns=`repeat(${size}, 1fr)`;boardEl.innerHTML='';cells.forEach(cell=>{let button=document.createElement('button');button.className='mine-cell'+(cell.revealed?' revealed':'')+(cell.mine&&cell.revealed?' mine':'');button.textContent=cell.revealed?(cell.mine?'*':(cell.count||'')):(cell.flagged?'!':'');button.addEventListener('click',()=>reveal(cell));button.addEventListener('contextmenu',event=>{event.preventDefault();if(!cell.revealed&&!gameOver){cell.flagged=!cell.flagged;minesEl.textContent=mines-cells.filter(item=>item.flagged).length;render();}});boardEl.appendChild(button);});}
startBtn.addEventListener('click',reset);reset();
